# Generated by Django 5.0.3 on 2024-05-18 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
