# Generated by Django 5.0.3 on 2024-04-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30)),
                ('price', models.FloatField(max_length=100000)),
                ('description', models.CharField(max_length=5000)),
                ('img_link', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
