# Generated by Django 5.0.3 on 2024-04-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img_link',
        ),
        migrations.AddField(
            model_name='products',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
