# Generated by Django 5.0.3 on 2024-04-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_products_img_link_products_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='goods_img'),
            preserve_default=False,
        ),
    ]
