# Generated by Django 5.0.3 on 2024-04-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100000)),
                ('image', models.ImageField(upload_to='main_images')),
                ('slug', models.SlugField(default='')),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'popular_products',
            },
        ),
    ]
